### ISSUE TITLE
Problem Set crashes

### ISSUE THREAD

**Issue by NetherDevil** [royqh1979/RedPanda-CPP#29]
The RedPanda-C++ hangs and crashes when running test cases as the program outputs a number of data.

Please try the following code and add a test case:
```cpp
#include <iostream>
int main(int argc, char** argv) {
	while (true) {
		cout << "Give it up";
	}
	return 0;
}
```
Click `Run All Cases`, and RedPanda-C++ stops responding.

I'm not sure if this is a bug, but my friend was annoyed about that.

**Comment by royqh1979** [comment]
Fixed in 0.14.0

**Comment by NetherDevil** [comment]
It won't crash now, but it is still slow when the output is very long.

I think it's better to output limit to the Problem Set runner.

**Comment by royqh1979** [comment]
Sure it will be slow, because we need to compare the real output against
the expected output, to check if the output is correct.
If what you really want is to redirect the program's input, you should use
"Execute" -> "running parameters" -> "redirect input to the following file"



NetherDevil ***@***.***> 于2022年2月6日周日 20:31写道：
